### ISSUE TITLE
Icon Fab UI is being triggered click event once scrolling through the bottom of the page on iPhone

### ISSUE THREAD

**Issue by jbuican14** [we-are-friend/we-are-blog#35]
https://drive.google.com/file/d/1YaMbiadL26kFJIE-NarsaAelAdnTSUCC/view?usp=sharing

**Comment by kitravee** [comment]
remove all of useCustomHook to detect viewport height and replace with https://material-ui.com/components/app-bar/#BackToTop.js

**Comment by kitravee** [comment]
#Done
please test -> https://we-are-blog.vercel.app/
@suthatta @Nattarintra @pathumwadee
